backend:
  name: github
  branch: main
  repo: thepashupatinathnews/thepashupatinathnews
media_folder: "public/uploads"
public_folder: "/uploads"
collections:
    - name: news
    label: News
    folder: content/news
    create: true
    fields:
            - {label: Title, name: title, widget: string}
            - {label: Date, name: date, widget: datetime}
            - {label: Image, name: image, widget: image}
            - {label: Body, name: body, widget: markdown}
