backend:
  name: github
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
    - name: "news"
        label: "News"    
        folder: "content/news"
        create: true
    fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Date", name: "date", widget: "datetime"}
            - {label: "Body", name: "body", widget: "text"}
